version: 1.0.0

connections:
- name: "local"
  provider: "SQLite"
  connectionString: "Data Source=:memory:; Version=3; New=True;"

actions:
- action: NonQuery
  name: "Create table"
  parameters:
    connection: "local"
    queries: 
    - |
      CREATE TABLE IF NOT EXISTS test (
        id INTEGER PRIMARY KEY AUTOINCREMENT, 
        name TEXT NOT NULL,
        description TEXT
      )    
     